// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "256f4f46-62ab-438c-98d7-e15855e20aa9";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBombaChange();

float hidrogenio;
float pH;
float tDS;
float temperatura;
bool bomba;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(hidrogenio, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(pH, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(tDS, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperatura, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(bomba, READWRITE, ON_CHANGE, onBombaChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
